fizzbuzz-sh: Bash/*
bash: Bash/*

c#: C#/*
fizzbuzz-c#: C#/*

c++: C++/*
fizzbuzz-cpp: C++/*

c: C/*
fizzbuzz-c: C/*

dart: Dart/*
fizzbuzz-dart: Dart/*

elixir: Elixir/*
fizzbuzz-elixir: Elixir/*

go: Go/*
fizzbuzz-go: Go/*

haskell: Haskell/*
fizzbuzz-haskell: Haskell/*

java: Java/*
fizzbuzz-java: Java/*

javascript: JavaScript/*
fizzbuzz-js: JavaScript/*

kotlin: Kotlin/*
fizzbuzz-kotlin: Kotlin/*

php: PHP/*
fizzbuzz-php: PHP/*

psql: PostgreSQL/*
fizzbuzz-psql: PostgreSQL/*

python: Python/*
fizzbuzz-py: Python/*

ruby: Ruby/*
fizzbuzz-ruby: Ruby/*

rust: Rust/*
fizzbuzz-rust: Rust/*

scala: Scala/*
fizzbuzz-scala: Scala/*

swift: Swift/*
fizzbuzz-swift: Swift/*

typescript: TypeScript/*
fizzbuzz-ts: TypeScript/*

hacktoberfest: ./*
hacktoberfest2020: ./*
